UN-OCHA/common-design-site

html/themes/contrib/common_design/package-lock.json, html/themes/contrib/common_design/package.json
downgrade eslint version to 5.16.0, attempt to fix issue with airbnb package
=> Attempt to fix eslint error on branch cd-183

composer.json, composer.lock
Resetting composer config to use tags for theme repo instead of feature branches
=> CD-187 more components deploy

composer.json, composer.lock, config/block.block.help.yml, config/block.block.languageswitcher.yml, config/system.menu.help.yml
with another menu block placed in header top to demo multiple user actions in global header
=> CD-177 deploy basetheme release 2.3.0

composer.json, composer.lock
To deploy 2.4.0 of common_design
=> CD-177 bump version for common_design to latest release

composer.json, composer.lock
Here's to not breaking the demo site!
1. bump theme release version to correct missing twig template error from subtheme
=> CD-177 deploy subtheme

composer.json, composer.lock
bump base theme release to fix demo site twig errors due to sub theme
=> CD-188 remove sub theme, fix demo site

composer.json, composer.lock
See https://github.com/UN-OCHA/common_design/releases/tag/v2.7.0
=> update base theme to 2.7.0

config/block.block.common_design_admin.yml, config/block.block.common_design_tools.yml, config/block.block.poweredbydrupal.yml, config/block.block.sidebarfirst.yml, config/block.block.sidebarsecond.yml, config/block_content.type.basic.yml, config/core.entity_form_display.block_content.basic.default.yml, config/core.entity_view_display.block_content.basic.default.yml, config/core.entity_view_mode.block_content.full.yml, config/core.extension.yml, config/field.field.block_content.basic.body.yml, config/field.storage.block_content.body.yml, config/language.content_settings.block_content.basic.yml, config/views.view.block_content.yml
add custom block type and place custom blocks in sidebars on relevant pages to demo layout
=> OPS-6742 export config so deploy succeeds

composer.json, composer.lock, html/modules/contrib/paragraphs_edit/README.md, html/modules/contrib/paragraphs_edit/paragraphs_edit.info.yml, html/modules/contrib/paragraphs_edit/paragraphs_edit.module, html/modules/contrib/paragraphs_edit/src/Form/ParagraphCloneForm.php, html/modules/contrib/paragraphs_edit/src/Form/ParagraphDeleteForm.php, html/modules/contrib/paragraphs_edit/src/Form/ParagraphEditForm.php, html/modules/contrib/paragraphs_edit/src/ParagraphFormHelperTrait.php, html/modules/contrib/paragraphs_edit/src/ParagraphLineageInspector.php, html/modules/contrib/paragraphs_edit/src/ParagraphLineageRevisioner.php, html/modules/contrib/social_auth_hid/composer.json, html/modules/contrib/social_auth_hid/social_auth_hid.info.yml, html/modules/contrib/social_auth_hid/social_auth_hid.install
bump base theme version to 2.8
=> CD-201 Update base theme

composer.lock
run `composer update unocha/common_design`
=> Update base theme v.2.8.2

.github/workflows/docker-build-image.yml
=> [OPS-6854] Fix the broken workflow yaml, so builds may work.

composer.lock, config/.htaccess
=> Update base theme

docker/services.yml
For demo site, so we can investigate and discuss use of template overrides for paragraph types
=> Enable twig debug

html/sites/demo.services.yml
=> Enable twig debug attempt 2

composer.lock, config/core.entity_view_display.media.image.default.yml, config/language.negotiation.yml, html/modules/contrib/ocha_media_content/config/optional/responsive_image.styles.responsive_image.yml, html/modules/contrib/ocha_media_content/config/optional/responsive_image.styles.responsive_thumbnail.yml
correct merge conflict, update ocha_media_content module from master repo
=> CD-198 media module

.github/workflows/docker-build-image.yml
Also, whilst I'm at it, try to do a docker login so that we do not hit
the anonymous pull limits that will be imposed soon.
And, for good measure, bump to the -develop PHP 7.3 image.
=> [OPS-7069] Ensure a new build is triggered on push to any branch named feature/*

composer.json, composer.lock
For fix release https://github.com/UN-OCHA/common_design/releases/tag/v2.8.7
=> bump base theme version

composer.json, composer.lock
So config imports and because this is preferred. I like using Devel generate for content population
=> install devel as non-dev

composer.json, composer.lock, html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig, html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-global-header.html.twig
As per AR-208 this should fix the Username variable caching issue, with a base theme update.
Also included are some improvements to the OCHA Services menu. To accommodate the moving of the OCHA Services partial to the footer, I've made the same changes in the sub theme.
=> CD-246 update base theme

.travis.yml, composer.json, composer.lock
- Core security update
- Base theme major release
=> OPS-7442 update Drupal core and base theme

composer.json
throw stuff at the wall and see what sticks
=> [OPS-7440] run E2E with npm instead of straight node

.travis.yml
=> OPS-7440 disable running e2e in Travis

translations/README.md, translations/ar-common-design.po, translations/es-common-design.po, translations/fr-common-design.po
=> CD-258 translation files for elements in the common design header and footer

composer.json, composer.lock, html/sites/default/default.services.yml
https://humanitarian.atlassian.net/browse/OPS-7780
=> [OPS-7634] update core to 9.2.6

config/theme_switcher.rule.term_edit.yml
- adjust request path for taxonomy terms to include the confirm delete page
=> Theme switcher settings 

.github/workflows/dispatch-site-build.yml, .github/workflows/docker-build-image.yml
I'm not at all sure if this will work as intended for the theme repo push hook. We'll see, I guess :-)
=> [OPS-7183] Be consistent

composer.json, composer.lock, html/sites/default/default.services.yml, html/sites/default/default.settings.php
https://humanitarian.atlassian.net/browse/OPS-8028
https://humanitarian.atlassian.net/browse/OPS-8029
=> [OPS-8028] update core to 9.3.3

.github/workflows/dispatch-site-build.yml, .github/workflows/docker-build-image.yml, composer.json, composer.lock, config/seckit.settings.yml, config/theme_switcher.rule.term_edit.yml, html/sites/default/default.services.yml, html/sites/default/default.settings.php, package-lock.json
https://humanitarian.atlassian.net/browse/OPS-8028
Security update for core.
=> [OPS-8028] security update

composer.json, composer.lock
=> [OPS-8028] make version bump clearer and add composer plugin permissions

composer.json, composer.lock, config/social_auth_hid.settings.yml, html/sites/default/default.services.yml
https://humanitarian.atlassian.net/browse/OPS-8135
=> [OPS-8135] bump social_auth_hid and small updates for other modules

composer.json, composer.lock, composer.patches.json, config/core.extension.yml, config/seckit.settings.yml
=> chore: improvements for seckit

PATCHES/csp-log-format.patch, composer.json, composer.patches.json
=> fix: patch csp for clearer logs

composer.json, composer.lock
=> Deploy 27-07-2022

config/csp.settings.yml
Refs: OPS-8232
Changes already made in the UI - this just to keep the code up-to-date.
=> fix: update csp config

composer.json, composer.lock
Refs: [OPS-8550](https://humanitarian.atlassian.net/browse/OPS-8550)
Core and module updates
=> Deployment 17-08-2022

config/theme_switcher.rule.node_bundle.yml
=> chore: update block visibility configuration

.github/workflows/composer-update.yml, composer.lock, config/csp.settings.yml, config/theme_switcher.rule.node_bundle.yml, html/sites/default/default.services.yml, package-lock.json, package.json
=> [OPS-8623] core security update 

config/core.entity_view_display.media.image.full.yml, config/core.entity_view_display.media.image.hero.yml, config/core.entity_view_display.media.image.media_library.yml, config/core.entity_view_display.media.video.media_library.yml, config/editor.editor.full_html.yml, config/facets.facet.content_type.yml, config/facets.facet.search_content_type.yml, config/views.view.facets.yml, config/views.view.media.yml, config/views.view.media_library.yml
Refs: CD-423
Doing some importing and exporting of config for the custom search feature and noticed some unrelated config that keeps getting changed owing to defaults but which makes the actual changes a little harder to pinpoint. Moving them to this PR so the other can be used as a reference for implementing search on other sites.
This PR should be completely harmless, if you think it isn't, do flag it!
=> chore: update config settings as exported

composer.patches.json
=> Patch to fix the search_api_solr config issue

composer.patches.json
=> Deploy 22-11-2022 search_api_solr patch

composer.json, composer.lock
=> CD-411 Update base theme to recent release

composer.json, composer.lock, composer.patches.json
Refs: CD-411
This uses the most recent base theme release https://github.com/UN-OCHA/common_design/releases/tag/v7.3.0
=> Deploy 22-11-2022 Base theme update

composer.json, composer.lock, config/core.menu.static_menu_link_overrides.yml
Refs: CD-254
Needs composer run and a `drush cim` to import the menu config
=> Update base theme to latest patch release 7.4.1

composer.json, composer.lock, config/core.extension.yml, config/google_tag.container.default.yml, config/google_tag.settings.yml
Refs: CD-449
Awaiting ansible config from down undah.
=> chore: add/enable/configure GTM with fake ID

composer.json, composer.lock
Refs: CD-448 and https://unhumanitarian.slack.com/archives/C03HKJXQ6EA/p1678344341106019
=> chore: use packagist not github for ocha_search

composer.lock, composer.patches.json
=> chore: remove patch so periodic updates can run

composer.json, composer.lock
Refs: OPS-9348
Seems to work okay.
=> chore: remove preserve-paths and adjust config

composer.json, composer.lock, config/pwa.config.yml, config/pwa_extras.settings.apple.yml, config/system.menu.help.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.theme, html/themes/custom/common_design_subtheme/templates/block/ocha-search-block.html.twig, html/themes/custom/common_design_subtheme/templates/layout/page--node--38.html.twig, html/themes/custom/common_design_subtheme/templates/layout/page--node--39.html.twig, html/themes/custom/common_design_subtheme/templates/layout/page.html.twig
I've had to make various corrections to our sub-theme overrides as I work on CD tickets. This PR holds them all.
=> Misc fixes

html/themes/custom/common_design_subtheme/components/cd/cd-header/cd-logo.css
Refs: CD-475, c05338f8, https://github.com/UN-OCHA/common_design/pull/407
=> fix: unset custom mobile logo at desktop bkpt

.github/workflows/run-tests.yml
=> chore: fix access key variable

composer.json, composer.lock
=> feat: Add openid_connect_windows_aad for B2C logins.

config/environment_indicator.switcher.demo.yml, config/environment_indicator.switcher.feature.yml, config/environment_indicator.switcher.prod.yml, config_dev/environment_indicator.indicator.yml, config_dev/environment_indicator.switcher.local.yml
=> chore: update environment indicator config

composer.lock
Adds Disclosure to the Demo
Refs: CD-489
=> chore: update CD to latest release

composer.lock, config/filter.format.full_html.yml, html/themes/custom/common_design_subtheme/package-lock.json
Refs: CD-497 remove config to enable D10 upgrade.
=> Deploy 01-11-2023 Part 1

composer.lock
=> chore: update ocha_integrations module

composer.lock
=> chore: update ocha_integrations module again

composer.json, composer.lock, config/core.extension.yml, local/docker-compose.yml
Refs: CD-497
Not sure why adding Classy was prompted in the transition to D10 - this removes it again.
=> chore: remove classy theme

composer.json, composer.lock, config/core.extension.yml, local/docker-compose.yml
=> Deploy 01-11-2023 - Part 4

local/README.md, local/docker-compose.yml, local/install.sh
From https://github.com/UN-OCHA/unocha-site/tree/develop/local
=> Update local folder with most recent from unocha for consistency

local/.env.example, local/shared/settings/services.yml
=> chore: update local stack for consistency

config/facets.facet.content_type.yml, config/facets.facet.search_content_type.yml
chore: change facet widget from select_a11y to checkboxes, as select_a11y is not working
Refs: CD-511
=> CD-511change facet widget from select_a11y to checkboxes

tests/vrt/anon_urls.txt, tests/vrt/auth_urls .txt
=> CD-532 URLs for VRT

local/docker-compose.yml
=> bump local mysql version

composer.lock, composer.patches.json
=> updates: remove blocking patch and update modules

composer.json, composer.lock
Mainly to test if the latest PRs for CD-514 are making google happy.
=> chore(deps): unocha/common_design:^9.4.0

composer.json, composer.lock
=> Deploy 20-03-24 with CD latest version

.github/workflows/run-tests.yml
Refs: OPS-10218
I think this does what we want, but shouldn't find out until we make a PR to main.
=> tests: include composer-lock diff in PRs to main

config/seckit.settings.yml
=> chore: more csp configuration

config/seckit.settings.yml
=> chore: allow more google tracking

config/seckit.settings.yml
=> chore: remove ad domains from csp

config/seckit.settings.yml
=> chore: add more csp allowances for google site search

config/core.extension.yml
=> chore: uninstall sdc module

PATCHES/user_expire-customize-notification-email.patch, PATCHES/user_expire-reset-expiration-on-reactivation.patch, composer.lock
=> chore: update patches for user_expire

.github/workflows/run-tests.yml
=> chore: use v2 of docker compose for tests

composer.patches.json
=> chore: add patch to avoid error on facet pages

config/core.extension.yml
=> chore: enable select_a11y_facets module for plugin discovery

config/seckit.settings.yml
=> chore: add google ad domains for CSP

CHANGELOG.md, composer.json, composer.lock
=> chore: update changelog

config/seckit.settings.yml
=> chore: disallow data: for csp

CHANGELOG.md, composer.json, composer.lock, config/seckit.settings.yml, html/sites/default/default.settings.php
* Csp restore data for img-src ([06a6c8](https://github.com/UN-OCHA/common-design-site/commit/06a6c8ec0902e4326cb61257c636a700bac8f0f3))
* Disallow data: for csp ([949f5e](https://github.com/UN-OCHA/common-design-site/commit/949f5e6c6fdd14778544b2a92628516370c729ea))
* Update all outdated drupal/* unocha/* drush/* packages. ([f80c59](https://github.com/UN-OCHA/common-design-site/commit/f80c59b80e9b1bfdda487c029c87aa5f8687463d), [78b3e7](https://github.com/UN-OCHA/common-design-site/commit/78b3e743a92aab1eaef95801674750f3c59e8889), [d528d2](https://github.com/UN-OCHA/common-design-site/commit/d528d2ef32efd23873cf49b7f709fa93ea78dd0a), [92c1c4](https://github.com/UN-OCHA/common-design-site/commit/92c1c42fdc21140c71264f7473c2ae5a51663c45), …
=> Deploy 19-11-2024
